---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nfs-subdir-external-ssd
  namespace: default
spec:
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external
        namespace: flux-system
      version: 4.0.18
  interval: 60m
  values:
    nfs:
      server: 192.168.1.230
      path: /srv/nfs
    storageClass:
      accessModes:
        - ReadWriteMany
        - ReadWriteOnce
        - ReadOnlyMany
      name: nfs-client-ssd
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
  install:
    createNamespace: true
    remediation:
      retries: 5
